### ISSUE TITLE
VueTrix in a loop

### ISSUE THREAD

**Issue by thibaultchazal** [hanhdt/vue-trix#52] opened 2019-07-18 16:01 UTC
Hey, thanks for your work !

I have an issue using VueTrix multiple times in one component (in a v-for loop) but It keeps one value.
```js
<VueTrix v-if="currentItem" v-model="currentItem.consigne" placeholder="Rajouter une consigne"/>
```

I tried using inputs but I never get to do it works properly. 
```js
<input :id="`trix-input-${currentItem._id}`" type="hidden" :value="currentItem.consigne">
<VueTrix :inputId="`trix-input-${currentItem._id}`" placeholder="Enter content"/>
```

Either it keeps one value for every instance or it doesn't update the vue variable (currentItem.consigne here). I tried either to keep it inside the component with the loop and in an other component. Same results.

Do you know what's going on ?

**Comment by hanhdt** [comment] 2019-07-18 23:49
Hi,
Thanks for using component.
I tried to reproduce your situation from my side. Just one point, I want to confirm what you had put into `v-model`? is that change for each instance of `VueTrix`?

**Comment by thibaultchazal** [comment] 2019-07-19 08:01
Hi hanhdt, sorry for the very short piece of code I shared.

Yes it is, I have in fact two VueTrix instance in my component : 
'''js
<input :id="`trix-input-${currentItem._id}`" type="hidden" :value="`${currentItem.consigne}`">
<VueTrix :inputId="`trix-input-${currentItem._id}`" v-model="currentItem.consigne" placeholder="Rajouter une consigne"/>

<input :id="`trix-input-${currentItem._id}`" type="hidden" :value="`${currentItem.conclusion}`">
<VueTrix class="" inputId="conclusion" v-model="currentItem.conclusion" placeholder="Rajouter une conclusion"/>
'''

But it's not in a loop (old component I get back into... sorry...) but it's a single component and the v-model variable "currentItem" is updated on event by a method. My problem is in the 'VueTrix' instance, the value is not updated on event although I see in the console the hidden input value is.

Is it clear enough ?

**Comment by hanhdt** [comment] 2019-07-20 00:58
Hi @thibaultchazal ,
Thanks for explaining. I got the issue.
Actually it’s a technical problem for now.
`VueTrix` could not two-ways binding data reactively. It means any changes from `v-model` will not reflect on the editor UI.

**Comment by RayForst** [comment] 2019-07-27 20:44
Got the same problem. Any ways to deal with it?

**Comment by hanhdt** [comment] 2019-07-28 02:50
Yes, it have work around, actually I did it before. But also it comes with side-effect.
When tracking changes from `v-model` and then replace HTML content of Trix editor, because Trix API will move the cursor to end of paragraphs even you're in the middle of paragraph.
That is another side issue.

**Comment by jsd219** [comment] 2019-08-29 12:00
@hanhdt You mentioned above you have a work around. What is it? can you give an example?

**Comment by hanhdt** [comment] 2019-08-29 23:34
@jsd219 Yes, I need change `VueTrix` codes, hence I will create new branch. And then notify you soon?

**Comment by jsd219** [comment] 2019-08-30 02:45
@hanhdt Do you need these codes from me?

**Comment by hanhdt** [comment] 2019-08-30 06:31
@jsd219 Yes, it would be better, if you can share codes from your side.

**Comment by jsd219** [comment] 2019-08-30 12:25
I tried to clear out as much additional code as possible to give a clear understanding of what is going on. 

Here is the user flow. the user has two choices. they can edit the content in the builder component or they can open the wizard and edit the content inside the wizard. currently when the user edits the content in the builder and **then** opens the wizard I have a method "getClue" that updates the wizard so it has the correct content but when the user edits the content in the wizard and **closes** the wizard the builder does not update the content. 

I have tried things like re-init the code and that works in Chrome and Firefox but it does **not** work in Safari. I am looking for a way to update the editor once the wizard has closed. 

Let me know if this is unclear and/or you need more of the code. 

Thank you all of your help

below is code inside the Builder:

HTML:

```
<div>
	
	<Wizard v-if="clueData" :clueData="clueData" @close="showWizardForm=false"/>

	<v-flex xs12 sm6 md4 lg3 v-for="(item,i) in clues" :key="i">
		
		<div>
			<span class="btn-floating btn-small purple wizard" @click="getClue(item.gid,item.order,engageWizard=true)">
                <v-icon dark>location_on</v-icon>
            </span>
		</div>

		<v-card-text class="subheading">
		    <VueTrix class="trix-content responsive" id="clue" :inputId="'cluemsg-'+item.id" v-model="item.message" placeholder="enter your content..."/>
		</v-card-text>

	</v-flex>

</div>
```

Script:

```
mounted() {

    // watch the VueTrix for changes including formatting 
    document.addEventListener( 'trix-change', ( event ) => {

        let inputid
        inputid = event.target.attributes[1].value
    
        event.target.classList.add("saving");
        this.startTypingTimer(event.target.parentElement.id, {message:event.target.innerHTML, id:inputid, target:event.target})

    }, false)

    document.addEventListener( 'trix-focus', ( event ) => {
        var x = document.getElementById(event.target.attributes[1].value).parentElement;
        x.classList.add("show-toolbar");
    })

    document.addEventListener( 'trix-blur', ( event ) => {
        var x = document.getElementById(event.target.attributes[1].value).parentElement;
        x.classList.remove("show-toolbar");
    })

}

startTypingTimer(collection, item, element) {
    
    clearTimeout(this.typingTimer)
    this.typingTimer = setTimeout(() => {
        this.save(collection, item, element)
    }, 300)
    
}

clearTypingTimer() {
    clearTimeout(this.typingTimer)
}

save(collection, item, element) {
    if(collection == 'clue') {

        var eleId = item.id.split("-")
    
        db.collection('XXXX').doc(eleId[1]).update({
            message: item.message
        }).then(() => {
            item.target.classList.remove("saving")
        }).catch(err => {
            console.log(err)
        })
        
    }
  
}
```

below is code inside the Wizard:

WIZARD:

```
<v-flex xs12 md6>
    <VueTrix class="trix-content wizard-clue-editor" id="clue" :inputId="'wiz-'+clueData[0].id" v-model="clueData[0].message" placeholder="enter your content..."/>
</v-flex>
```

**Comment by jsd219** [comment] 2019-08-31 03:00
I forgot to add the query. its a real time query from firestore

```
init(gid) {
            this.clues = []

            let cluesRef = db.collection('clues')
            cluesRef = cluesRef.where('XXXX', '==', gid)
            cluesRef = cluesRef.orderBy('order')
            cluesRef.onSnapshot(snapshot => {
                var c = []
                snapshot.forEach(doc => {
                    this.clue = doc.data()
                    this.clue.id = doc.id
                    c.push(this.clue)
                })
                this.clues = c
            })
}
```

**Comment by hanhdt** [comment] 2019-08-31 03:36
Thanks for your sharing.
I’m looking at codes and support to create new branch of `VueTrix`.

**Comment by hanhdt** [comment] 2019-08-31 05:15
@jsd219 You can try [this branch](https://github.com/hanhdt/vue-trix/tree/feature/two-ways-binding) now. Let me know if it's suitable to your situation.

**Comment by jsd219** [comment] 2019-08-31 12:36
forgive my ignorance but how do I update VueTrix with this new branch. I re-ran `npm install --save vue-trix` and when I run `npm view vue-trix version` it says I have 1.0.0

**Comment by hanhdt** [comment] 2019-08-31 12:56
You need install from Github branch some thing like: `npm install --save username/repo#branch-name-or-commit-or-tag`

**Comment by jsd219** [comment] 2019-08-31 12:59
ok so in this case it would be: `npm install --save jsd219/repo#feature/two-ways-binding` ?

**Comment by hanhdt** [comment] 2019-08-31 13:21
No, it should be from mine `hanhdt/vue-trix` unless you already have a folk.

**Comment by jsd219** [comment] 2019-08-31 13:45
I just ran `npm install --save hanhdt/vue-trix` and now I am getting a Failed to compile error.

**Comment by hanhdt** [comment] 2019-08-31 13:56
Sorry, I forgot push `dist`. Could you update it with `npm update`?

**Comment by jsd219** [comment] 2019-08-31 13:59
confirmed `"vue-trix": "github:hanhdt/vue-trix#feature/two-ways-binding",`

**Comment by jsd219** [comment] 2019-08-31 14:01
it appears to be working at first glance but i have noticed that every time I make a change in the editor it resets the focus

**Comment by hanhdt** [comment] 2019-08-31 14:02
Yes, it is one side-effect that why I didn't go with this before. Still looking for better solution.

**Comment by jsd219** [comment] 2019-08-31 14:03
ok, how do I roll it back to the previous version. I think I need to wait for a better solution :)

**Comment by hanhdt** [comment] 2019-08-31 14:05
Just change back your `package.json` with `"vue-trix": "^1.0.0"` and then `npm install` again.

**Comment by jsd219** [comment] 2019-08-31 14:14
ok thank you. please let me know when you find a better solution. Thank you for the plugin :)

**Comment by jsd219** [comment] 2019-08-31 14:22
I reverted back but I am still getting the reset focus issue

**Comment by hanhdt** [comment] 2019-08-31 14:24
Yes, you should try re-install it.

**Comment by hanhdt** [comment] 2019-08-31 15:38
@jsd219 I think I already found out a better solution. Please, try the branch again and test it the reset cursor's position focus issue should be resolved! :)

**Comment by jsd219** [comment] 2019-08-31 17:55
Hi @hanhdt sorry for the delay, I just saw this. I will pull this branch again and report back. :)

**Comment by hanhdt** [comment] 2019-09-02 06:59
Hi @jsd219 , it already merged into `master` and you can install it as a new version.
Thanks for pushing me on this. ;)

**Closed** 2019-09-03 14:08 UTC
Labels: enhancement
